title: Xin Yuan's Homepage
page-top-title: Xin Yuan
top-section-bg-text: Electrical Engineering
home-subtitle: Xin Yuan&ensp;|&ensp;Xin Yuan
copyright-text: '&copy; Xin Yuan 2023-2026. All Rights Reserved.'
